#!/bin/bash

echo "🔧 Quick Fix for BlogWeb Render Deployment Issues"
echo "================================================"

echo "✅ 1. Backend service configuration ready"
echo "✅ 2. CORS updated to include your deployed domain"
echo "✅ 3. Health check endpoint available"
echo "✅ 4. Frontend environment variables configured"

echo ""
echo "🎯 IMMEDIATE ACTION REQUIRED:"
echo ""
echo "1. 🌐 Go to: https://render.com/dashboard"
echo ""
echo "2. 🔧 Create NEW Web Service with these settings:"
echo "   - Repository: Truptid07/BlogWeb"
echo "   - Name: blogweb-backend"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo ""
echo "3. ⚙️  Add Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   JWT_SECRET=8f2a9c4d6b1e3f7a5c9d2e8f4a6b9c1d3e7f2a5c8d1e4f7a2c5d8e1f4a7b9c2e5f8a1d4e7f2a5c8d1e4f7a2c"
echo "   CLOUDINARY_CLOUD_NAME=blog"
echo "   CLOUDINARY_API_KEY=761868572134681"
echo "   CLOUDINARY_API_SECRET=TxShcWM1Xhq7GvZHKiwVWtQLcEM"
echo "   MONGODB_URI=mongodb+srv://sample:sample123@cluster0.emi78dg.mongodb.net/blogplatform?retryWrites=true&w=majority&appName=Cluster0"
echo ""
echo "4. 🎨 Update your existing frontend service:"
echo "   - Add Environment Variable:"
echo "   REACT_APP_API_URL=https://blogweb-backend.onrender.com/api"
echo ""
echo "5. 🔄 Redeploy both services"
echo ""
echo "6. 🌱 After backend is running, seed the database:"
echo "   - Go to backend service → Shell"
echo "   - Run: node seedDatabase.js"
echo ""
echo "🧪 Test URLs after deployment:"
echo "Backend Health: https://blogweb-backend.onrender.com/api/health"
echo "Frontend: https://blogweb-1-rpu1.onrender.com"
echo "API Test: https://blogweb-backend.onrender.com/api/blogs"
echo ""
echo "🔐 Admin Login:"
echo "Email: admin@example.com"
echo "Password: admin123"
echo ""
echo "🚀 Your BlogWeb will be fully functional after these steps!"