services:
  # Backend API Service
  - type: web
    name: blogweb-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: blogweb-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false  
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Static Site
  - type: static
    name: blogweb-frontend  
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: blogweb-mongodb
    databaseName: blogplatform
    user: bloguser
    plan: free